dod-ccpo/atat-web-api

.gitignore
README.md
poc/random_quote/jest.config.js
poc/random_quote/src/__tests__/post.test.ts

Updated jest config to provide coverage reporting

---

poc/shared_infrastructure/main.tf

Added this to the terraform configuration:
- resource of type `azurerm_servicebus_namespace`
Ticket: AT-6321

Integrate Service Bus

---

poc/shared_infrastructure/terraform.tfvars.template

This template communicates the expected variables to be provided to terraform.

add templated version of tfvars

---

.github/workflows/test.yml
README.md
poc/random_quote/.eslintrc.json
poc/random_quote/package-lock.json
poc/random_quote/package.json
poc/random_quote/src/__tests__/get.test.ts
poc/random_quote/src/__tests__/post.test.ts
poc/random_quote/src/handlers/get.ts
poc/random_quote/src/handlers/post.ts
poc/random_quote/src/util/quotes_helper.ts

Added initial files for eslint and workflow for github

---

README.md

Merging of #24 requires update to navigation commands in the README

Update README navigation commands

---

README.md

Re-adds some of the previous intro content linking atat repos together.

add some introductory info to README

---

infrastructure/package.json

Pass `--fix` option to `npm run lint`
https://stackoverflow.com/a/58954298

fix script lint:fix

---

README.md

Adds sections:
- Install Prerequisites (includes table and commands)
- Install JavaScript Dependencies

add sections to README

---

applications/portfolioDrafts/models/PortfolioStep.ts
applications/portfolioDrafts/portfolio/createPortfolioStep.ts
applications/portfolioDrafts/utils/validation.ts

Added a conditional expression on the `UpdateCommand` to check if the `created_at` attribute exists on the `Item`.
`created_at` was chosen because you cannot check for the PK with `attribute_exists()`.
Changes `updated_at` with the current time: 
```
const now = new Date().toISOString();
```

Update createPortfolioStep function to add portfolioDraftId validation, fix timestamp

---

applications/portfolioDrafts/createPortfolioDraft.ts
applications/portfolioDrafts/getPortfolioDrafts.ts
applications/portfolioDrafts/index.ts
applications/portfolioDrafts/models/PortfolioDraftSummary.ts
atat_provisioning_wizard_api.yaml
infrastructure/lib/atat-web-api-stack.ts

Implements function `getPortfolioDrafts`.
_Note Well:_
Function uses expensive [Scan](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/scancommand.html) command to return all items in table.  This should be refactored in time as authenticated users are introduced and table is optimized for 1:many User-to-PortfolioDraft access.
Also, DynamoDB implementation will not work with numeric _offset_, so a different solution is required.  I expect a future API spec change to remove query parameter _offset_ from this operation.  That will likely be replaced with an alternative cursor-type approach involving DynamoDB's `LastEvaluatedKey` element and  `ExclusiveStartKey` parameter.
TODO:
Ticket: AT-6362

Implement 'getPortfolioDrafts' function

---

infrastructure/lib/atat-web-api-stack.ts
packages/api/models/Clin.ts
packages/api/models/CloudServiceProvider.ts
packages/api/models/FileMetadataSummary.ts
packages/api/models/FundingStep.ts
packages/api/models/ProvisioningStatus.ts
packages/api/portfolioDrafts/createPortfolioDraft.ts
packages/api/portfolioDrafts/funding/createFundingStep.ts
packages/api/portfolioDrafts/portfolio/createPortfolioStep.ts
packages/api/utils/validation.ts

Implements core functionality of function.  Lacks validation and error map.
- Define function `CreateFundingStepFunction` and add to stack
- Add `funding` route for _/portfolioDrafts/{portfolioDraftId}/funding_
- Add models `FundingStep`, `FileMetadataSummary`, and `Clin`
- Add enum `CloudServiceProvider`
- Add validation function isFundingStep()
- Some PR review advice was applied to implementation of other functions
Ticket: AT-6409

Implement 'createFundingStep' function

---

infrastructure/lib/atat-web-api-stack.ts
packages/api/portfolioDrafts/funding/getFundingStep.ts

Implements function `GetFundingStepFunction`
- Defines function and adds to stack.
- Adds GET method to existing route '/portfolioDrafts/{portfolioDraftId}/funding'
Ticket: AT-6408

Implement function 'GetFundingStepFunction'

---

.github/workflows/test.yml
infrastructure/bin/atat-web-api.ts
infrastructure/package-lock.json
infrastructure/package.json

This adds support for running with CDK Nag enabled. It is not a goal to
resolve all of the issues in this PR, just to make ourselves aware of
them.

Add cdk nag

---

infrastructure/lib/atat-web-api-stack.ts
packages/api/portfolioDrafts/getPortfolioDraft.test.ts
packages/api/portfolioDrafts/getPortfolioDraft.ts
packages/api/portfolioDrafts/portfolio/createPortfolioStep.ts

Includes unit test with mock DynamoDB client. Nothing fancy here.
Ticket: AT-6487

Implement function 'GetPortfolioDraft'

---

packages/api/portfolioDrafts/createPortfolioDraft.ts
packages/api/portfolioDrafts/funding/getFundingStep.ts
packages/api/portfolioDrafts/portfolio/getPortfolioStep.ts
packages/api/taskOrderFiles/uploadTaskOrder.ts
packages/api/utils/errors.ts

Attempt to make the implementations from different sprints by different developers have more similarities

Refactor all the things

---

atat_provisioning_wizard_api.yaml

Funding Step now features an array called `task_orders`
- Added a second task order under `task_orders`
- Applied values _accepted_ and _pending_ for `status`
- Applied values _aws_ and _azure_ for `csp`
- Used uuidv4 for file `id`
- Used PDF filenames for `name`
- Used feasible byte count for `size`
Application Step now features an array called `applications`
- Added second application under `applications`
- Applications not have one environment each rather than one application with two environments
- Tweaked application names and descriptions and environment names for clarity of purpose
Related to #140

Update examples in 'FundingStepEx' and 'ApplicationStepEx' to reflect recent updates to respective schema objects

---

packages/api/utils/validation.test.ts

Brings `validation.ts`  up to 100% coverage

Add unit test for isTaskOrder()

---

infrastructure/lib/constructs/api-function.ts
packages/api/package-lock.json
packages/api/package.json

This also reverts the workaround we added during the update to 3.33.0.

Update AWS SDK to 3.34.0

---

atat_provisioning_wizard_api.yaml
infrastructure/bin/atat-web-api.ts
infrastructure/lib/atat-web-api-stack.ts

This adds another environment variable to override this setting. By
default, authorization is required. It can be overriden with:
```
export ATAT_REQUIRE_AUTH=false
```

Conditionally require authorization

---

infrastructure/lib/constructs/authentication.ts

These are some standard attributes available from Azure AD.

Map additional attributes

---

infrastructure/lib/atat-web-api-stack.ts

Verified these are the correct operationIds, and last remaining API operations to be implemented.  Created corresponding Jira tickets.

Update TODO comments in API stack with outstanding API operationIds

---

infrastructure/lib/atat-iam-stack.ts

Grants all roles read access to AWS X-Ray.

Allow X-Ray access

---

atat_internal_api.yaml
infrastructure/lib/atat-web-api-stack.ts

This includes the first cut of new ATAT Internal API, which will eventually supplant the ATAT Provisioning Wizard API. No operations are implemented yet. We expect to start filling them out next Sprint.
Ticket: AT-6875

ATAT Internal API spec + APIGW instance

---

infrastructure/lib/constructs/compliant-resources.ts

This enables access logs in addition to the execution logs that we had
previously. This will provide additional information and context around
requests.

Enable API Gateway access logs

---

atat_internal_api.yaml

These are the changes I went over with the team after standup today:
Combined "Access" objects with parent models & removed Application/Environment Detail models. Commented out User model for now.
Ticket: AT-6875

Updated Internal API Spec: tweaks for Users and Operators

---

atat_internal_api.yaml

Minor copy edits per Tom's functional review.

---

infrastructure/bin/atat-web-api.ts
infrastructure/lib/atat-web-api-stack.ts
infrastructure/test/atat-web-api-aws.test.ts

This supports the creation of multiple IdPs for login.
Requires dod-ccpo/atat-web-ui#405 before we can deploy related changes.

Support multiple IdPs

---

infrastructure/bin/atat-web-api.ts
infrastructure/lib/atat-web-api-stack.ts
infrastructure/lib/constructs/authentication.ts
infrastructure/test/atat-web-api-aws.test.ts

This PR sets us up to integrate with the IdP that Robert Branch from GD set up for us. It defines custom attributes using the names he gave us and then sets up the mappings accordingly.
Ticket: AT-6874

Added SAML IdP for GD

---

package-lock.json
package.json

This will prevent the attempted use of docker for CDK bundling

Add esbuild package as dev dependency

---

.gitignore
api/provision/mock-invocation-fn.test.ts
api/provision/mock-invocation-fn.ts
api/provision/result-fn.test.ts
api/provision/result-fn.ts
api/provision/start-provision-job.test.ts
api/provision/start-provision-job.ts
atat_provisioning_api.yaml
lib/atat-web-api-stack.ts
lib/constructs/provisioning-sfn-workflow.test.ts
lib/constructs/provisioning-sfn-workflow.ts
lib/constructs/provisioninng-sfn.test.ts
models/cloud-service-providers.ts
models/provisioning-jobs.ts
package-lock.json
package.json
utils/aws-sdk/sqs.ts
utils/middleware/error-handling-middleware.ts

Adding ResultFunction to Provisioning Step Function workflow. Its job is simply to take the results of the CSP Invocation step and put them onto a SQS Queue. 
Infrastructure added:
* NodeJs Lambda Function (`ResultFunction`)
* SQS Queue (`ProvisioningQueue`)
* IAM Policies for controlling access to the queue
Includes one infrastructure test and one code test.
Ticket: AT-7056

Implement 'Result Lambda' and 'Result Queue'

---

.secrets.baseline
lib/atat-iam-stack.ts
lib/atat-iam.test.ts

- Fix access to Step Functions
- Allow developers to read SQS Queues

Fix IAM permissions

---

package-lock.json

This performs a larger dependency update so that we don't have to handle
them all one-by-one with Dependabot.

Update multiple dependencies

---

.secrets.baseline
lib/aspects/govcloud-compatibility.ts
lib/atat-web-api-stack.ts
lib/constructs/api-user.test.ts
lib/constructs/api-user.ts
lib/constructs/apigateway.ts

Closes: https://github.com/dod-ccpo/atat-web-api/pull/804#issue-1212556241

Create IAM Users for Invoking HOTH API

---

hoth_api.yaml

There was a need for more data nesting (see [PR 70 ](https://github.com/dod-ccpo/atat-snow/pull/70)on atat-snow),
to support these changes the DOW schema needed to be updated.
- Removed RequiredServices schema
- Added SelectedServiceOffering
- Added ClassificationInstances
```
{
"award_history": [
{
"contract_award_type": "INITIAL_AWARD",
"modification_order": 0,
"effective_date": "2022-05-26"
}
],
"contract_information": {
"contract_number": "string",
"current_contract_exists": true,
"contract_expiration_date": "2022-05-26",
"incumbent_contractor_name": "string",
"task_order_number": "string",
"previous_task_order_number": "string"
},
"to_title": "string",
"scope": "string",
"scope_surge": 0,
"current_environment": {
"current_environment_exists": true,
"environment_instances": [
{ …
```

Update DOW schema to reflect table changes

---

lib/constructs/api-user.ts

Everything inside of me wants to cry about a PR that just adds a TODO
but this seems like the best way to document "this bit is doing the best
thing that we can do today but not the best thing that might ever be
possible." It's not an urgent fix that we need either. But just
something that this feels like the best way to give context around this
piece of code.

Add a TODO for better Access Key Secret structure

---

hoth_api.yaml

When designing the generateDocument lambda, it was better practice to declare what the `documentType` and `templatePayload` was at the top level of the schema. 
This change modifies the GenerateDocumentRequest schema to match what is currently utilized in
https://github.com/dod-ccpo/atat-web-api/pull/928
```
{
"documentType": "DESCRIPTION_OF_WORK",
"templatePayload": {
"award_history": [
{
"contract_award_type": "INITIAL_AWARD",
"modification_order": 0,
"effective_date": "2022-06-08"
}
],
"contract_information": {
"contract_number": "string",
"current_contract_exists": true,
"contract_expiration_date": "2022-06-08",
"incumbent_contractor_name": "string",
"previous_task_order_number": "string"
},
"to_title": "string",
"scope": "string",
"scope_surge": 0,
"current_environment": { …
```

Add more properties to the GenerateDocumentRequest schema

---

api/cost/start-cost-job.test.ts
models/cost-jobs.ts

I realized that I had totally forgotten about this property right as the original PR merged. Woops!
Ticket: AT-7628

Added targetCsp property to CostRequest model

---

lib/atat-iam-stack.ts
lib/atat-net-stack.ts
lib/atat-net.test.ts

See the individual commits within the PR for more details on each change.
- Allow developers to purge SQS queue
- Log all DNS queries to CloudWatch Logs

Make modifications based on recent Lambda error

---

lib/atat-iam-stack.ts

This will enable easier testing of functionality that relies on sending messages to a particular Queue.

AT-7458: Granting Developers the sqs:SendMessage action

---

lib/atat-iam-stack.ts

Allow sending, recieving, and purging queues for funcitonal testing.

Revert SQS permission for testing in Dev

---

api/util/csp-request.test.ts
api/util/csp-request.ts

This reverts commit 6a2cbe6bce3e89d878d9440057f1b24c3f45d7eb.

Revert mock cost response

---

api/cost/cost-request-fn.ts
api/cost/start-cost-job.ts
api/provision/csp-write-portfolio.ts
api/provision/result-fn.ts
api/provision/start-provisioning-job.ts
api/util/queueConsumer.ts
document-generation/generate-document.ts
lib/aspects/govcloud-compatibility.test.ts
lib/aspects/govcloud-compatibility.ts
lib/atat-net-stack.ts
lib/atat-web-api-stack.ts
lib/constructs/api-sfn-function.ts
lib/constructs/cost-api-implementation.ts
lib/constructs/provisioning-sfn-workflow.test.ts
lib/constructs/provisioning-sfn-workflow.ts
lib/constructs/vpc-endpoint-lb-target.ts
package-lock.json
package.json
utils/aws-sdk/secrets-manager.ts
utils/aws-sdk/sqs.ts
utils/aws-sdk/step-functions.ts
utils/tracing.ts

This feature is now supported in AWS GovCloud (US) so we can remove our
Aspect config for this and add the TracingConfig to all of our
functions!
See https://aws.amazon.com/about-aws/whats-new/2022/07/aws-lambda-supports-aws-x-ray-govcloud-us-regions/
Additional commits will add the AWS Lambda PowerTools features to all
our functions and patch our usage of the AWS SDK.

Add X-Ray Tracing Config for all Lambda functions

---

hoth_api.yaml

Add Asynchronous job response to HOTH API

---

.pre-commit-config.yaml
.secrets.baseline

`detect-secrets` released a new version, v1.4. This updates the `pre-commit` configuration and `.secrets.baseline`.

Update `detect-secrets` version

---

hoth_api.yaml

Adds `EvalPlan` schema to support _Evaluation Plan_ document generation
Ticket: AT-8376

AT-8376: Added first cut of EvalPlan object

---

hoth_api.yaml

- Create `Incremental Funding Plan` schema for generating IFP document in the HOTH API
- Update `GenerateDocumentRequest`
Ticket: AT-8379

Create IFP schema for HOTH API

---

hoth_api.yaml

Create `Requirements Checklist` schema.
Minor adjustment of `IncrementalFundingPlan` schema
- Fix amount `type`s to be `number`s and add `format`
Ticket: AT-8361

Create Requirements Checklist schema for HOTH API

---

hoth_api.yaml

- changed monthly_price to unit_price
- changed months_in_period to unit_quantity
- added contract_type field with enum of FFP or T&M
- contract type moved up in the schema to logically follow excel template
- modified description of unit_quantity, removed old months description and replaced
with units/quantity description to match template
- remove CLIN from PeriodLineItem, due to no longer needing it on the template
Added an `enum` for FFP or T&M
Ticket: AT-8385

Update IGCE Schema For Latest Document

---

api/client/client.ts

Remove request from being logged (axios object request).

Fix HOTH CSP response log

---

manual-steps/stig-remediation.ts

This keeps coming up in conversations and so we should just start
enabling it. There's no reason not to. We can just use the AWS-managed
key for now because we don't expect anything to use it _and_ that at
least ensures it's encrypted.

Add a step for encrypting EBS volumes

---

hoth_api.yaml

Refactor DOW schema based on latest DOW document for document generation.
Ticket: AT-8382

Refactor DOW schema for HOTH API

---

lib/atat-shared-data-stack.ts

Added description to the sns cmk and enable rotation on the key as well.

Set description and automatic rotation for KMS CMK

---

.secrets.baseline
cfn-templates/sso-permission-sets.cf.yaml

added permissions for auditor role to update finding statuses. This will allow chris sowells to resolve/suppress issues on his own.

added permissions for auditor role to update finding statuses

---

.secrets.baseline
cfn-templates/sso-permission-sets.cf.yaml

another action needed for the auditor AWS SSO role.

Allow BatchUpdateFindings action for security hub

---

api/client/client.ts

Update client to match ATAT CSP API specification.

Update client supported version

---

lib/constructs/provisioning-sfn-workflow.ts

need to revert changes to the key. Need to test properly on sandbox before pushing the dev.

reverting changes to secrets key for now

---

cdk.json
lib/atat-net-stack.ts
lib/atat-net.test.ts

updated the vpc flow logs to point from s3 bucket to a cloudwatch log group per C5ISR.

update flow log desc

---

cdk.json
lib/atat-net-stack.ts

updated the vpc flow log custom format with a missing parameter.

Add parameter instance-id to vpc flow logs

---

lib/atat-notification-stack.test.ts
lib/atat-notification-stack.ts

updated the list of API events to monitor to meet STIG compliance.

added to the list of events to monitor for user activity

---

cdk.json

switched back to the develop branch.

fixed suggested changes

---

document-generation/utils/dow.test.ts
document-generation/utils/dow.ts

Fixed issue where we were displaying row 4 even when we did not have TS service instances or XaaS instances

AT-8729: Bug fix

---

.secrets.baseline
cfn-templates/sso-permission-sets.cf.yaml

updated the QA role read permission for s3 and cloudtrail

updated the QA role read permission for s3 and cloudtrail

---

hoth_api.yaml

- Adds `JUSTIFICATION_AND_APPROVAL` as an option for `documentType`
- Adds schema `JustificationAndApproval`
Ticket: AT-8830

AT-8830: First cut of J&A document specification in HOTH API

---

.secrets.baseline
cfn-templates/sso-permission-sets.cf.yaml

added code commit and code pipeline read permissions for QA role

added code commit and code pipeline read permissions for QA role

---

.secrets.baseline
cfn-templates/sso-permission-sets.cf.yaml

added permissions to view default encryption for ec2 instance for the QA team

QA role - added permissions to view default encryption for ec2 instance

---

document-generation/igce-document.ts

It seem like IGCE doc template tool does not support if/else statement. Looking at other IGCE codes, it uses ternary operation instead of if/else statement.

changed if/else to ternary operation

---

document-generation/igce-document.ts

we have to made the same adjustment made to contracting fee to fix undefined grand total fee for ditco user

fix undefined grand total fee for ditco user

---

document-generation/ifp-document.ts

https://ccpo.atlassian.net/jira/software/c/projects/AT/boards/47?modal=detail&selectedIssue=AT-9428
added parameter to toLocalString() in IFP generation to round to 2 decimal places.

changed ifp values to round 2 decimal places

---

api/client/client.ts
api/client/types.ts
api/provision/csp-create-environment.test.ts
api/provision/csp-get-portfolio.test.ts
api/provision/csp-get-portfolio.ts
api/util/common-test-fixtures.ts
lib/constructs/provisioning-sfn-workflow.ts
models/provisioning-schemas.ts

Created all step-fn code for AWS functions
Created Tests and mocks for the client
Added handling for getting the portfolio based on Id from the CSP.

AT-9751: Implement GetPortfolio in HOTH Api

---

api/client/client.ts
api/client/types.ts
api/provision/csp-create-environment.test.ts
api/provision/csp-create-environment.ts
api/util/common-test-fixtures.ts

types/lambda updated with three new optional fields

AT-9971 types/lambda updated with three new optional fields
