poc/random_quote/serverless.yml
poc/serverless.common.yml

Added the jwtValidate to the serverless.common.yml which can be used later on when we need to have full integration with the api.
AT-6134

Added JWT config to the serverless common yml

---

poc/shared_infrastructure/main.tf
poc/shared_infrastructure/variables-network.tf

Replaces #9 since #6 was merged to `develop`.
Added these to the terraform configuration:
- resource of type `azurerm_cosmosdb_account`
- resource of type `azurerm_cosmosdb_sql_database` likely named _atat_
- resource of type `azurerm_cosmosdb_sql_container` named _users_
- resource of type `azurerm_cosmosdb_sql_container` named _portfolios_
Expects the following variables to be provided:
- `cosmosdb_account_name`
- `cosmosdb_database_name`
- `failover_location`
Ticket: AT-6315

Integrate Cosmos DB

---

poc/random_quote/.eslintrc.json
poc/random_quote/package-lock.json
poc/random_quote/package.json

This should resolve scenarios where we are seeing linter differences
between local and the CI pipeline (because the CI pipeline is correctly
linting JSON files whereas the npm setup is not).
Eventually we need to converge on having a shared .eslintrc.json file
for all of our functions (as much as possible) and possibly using a tool
like lerna to manage the various projects that we have in the repo;
however, for now here are the steps to follow to get _other_ projects in
sync with this PoC app config:
1. Install the `eslint-plugin-json` package as a dev dependency
```
npm install --save-dev eslint-plugin-json
```
2. Add `"plugin:json/recommended"` to the `extends` section of
`.eslintrc.json`
3. Update `package.json` to have `,.json` in the `lint` and `lint:fix`
commands.

Add JSON linting support

---

README.md

Major re-organization under these headers:
- Install Prerequisites
- Deploy Shared Infrastructure
- Deploy Azure Function Apps
- Support Information
Made _Deploy..._ sections generic to include `./poc` and newer `./provisioning`

Improve README organization and content update

---

.nvmrc

Allows `nvm install` and `nvm use` without params
- same version as `atat-web-ui` repo
- [AWS Lambda supports Node.js 14](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)

add .nvmrc and specify node 14

---

atat_provisioning_wizard_api.yaml

As we decomposed requirements to support the Funding Step of the Portfolio Wizard, we found that the original file upload design did not support the user experience that we want (allowing users to upload files BEFORE clicking Next), so the spec has been updated to support this such that the upload step occurs before saving off form data.

AT-6417: Update Wizard Spec to support upload flow

---

applications/portfolioDrafts/createPortfolioDraft.ts
applications/portfolioDrafts/models/Error.ts
applications/portfolioDrafts/utils/response.ts

This adds type safety around our response objects. It ensures that we provide a proper Error object that matches the API specification when returning an error response or that we provide a subclass of `BaseDocument` when returning a success response. Utilizing an `enum` for the status codes also adds type safety to ensure that we don't return a 200 when we return an error body. The less-safe abstract parent `Response` class is not exported. Possibly missing is a 30x `RedirectResponse` class but that is not currently defined in our API.
I believe that all error codes current defined in the specification and application are represented in these classes, enums, and interfaces.

Create an interface for responses and errors

---

atat_provisioning_wizard_api.yaml

Per the specification, HTTP status code [204 No Content](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204) should be used for successful responses without a body.

Use HTTP 204 for success without body (DELETE methods)

---

applications/portfolioDrafts/models/PortfolioStep.ts
applications/portfolioDrafts/portfolio/createPortfolioStep.ts
applications/portfolioDrafts/portfolio/post.ts
applications/portfolioDrafts/utils/response.ts
infrastructure/lib/atat-web-api-stack.ts

Implements `createPortfolioStep` function for AWS.
Inserts `portfolio_step` and all child elements into an existing Portfolio Draft item in DynamoDB.
- Includes resource creation for `portfolioDraftId` and `portfolio` routes.
- Includes creation of and grants ReadWrite to `createPortfolioStepFn`
This functionality was completed previously in #25 for Azure.
Ticket: AT-6368

Implement 'createPorfolioStep' function

---

atat_provisioning_wizard_api.yaml

Under PortfolioDraft:
- `porfolio` -> `portfolio_step`
- `funding` -> `funding_step`
- `application` -> `application_step`

Rename three wizard step properties in PortfolioDraft schema in API

---

atat_provisioning_wizard_api.yaml

Fixing a few issues in the Funding Step of the spec:
1) Added support for multiple CLINs per Task Order
2) Changed `funding_step.task_order_file_id` to contain the entire `FileMetadata` object and renamed it to `task_order_file` accordingly
3) Addded `funding_step.task_order_file.status` field to indicate file scanning status for uploaded task orders
Ticket: AT-6409

Update Wizard spec for Funding Step

---

package-lock.json
package.json

Pipeline had been failing at _Synthesize CDK template_ with error.
Error example:
>   Run cdk synth
>   npx: installed 14 in 1.884s
>   Cannot find module 'typescript'
Installed package `ts-node` following instructions at https://www.npmjs.com/package/ts-node#installation

Fix pipeline error "Cannot find module 'typescript'"

---

infrastructure/bin/atat-web-api.ts
infrastructure/lib/atat-web-api-stack.ts

This will quickly allow deployments to be isolated for developers.
During cdk deploy/diff/destroy a context variable named `TicketId` must be provided.
For example:
`cdk deploy -c "TicketId=AT1234"`
If the context variable is not supplied a warning is displayed.
> Hello Developer. You must provide a context variable named 'TicketId' to isolate your deployment from others.
>   For example...
>   $ cdk deploy -c "TicketId=AT1234"

Allow isolated deployments by supplying 'TicketId' context variable to CDK

---

.eslintrc.json
.gitignore
infrastructure/lib/atat-web-api-stack.ts
infrastructure/package.json
packages/api/models/Error.ts
packages/api/models/FileMetadata.ts
packages/api/package-lock.json
packages/api/package.json
packages/api/taskOrderFiles/createTaskOrderFile.ts

Implementation will take a file (with Content-Type: multipart/form) and save it off to the Pending S3 Bucket. A few notes:
1) There's a hard limit per request of 10MB because we have to go through API Gateway,. This should be OK given that our average PDF size is 100KB and max is 2MB.
2) We have raised the timeout from the default of 3s to 300s to accommodate very slow connections. No need to prematurely kill our lambdas here.
Ticket: AT-6417

First cut of POST /taskOrderFiles

---

packages/api/portfolioDrafts/funding/createFundingStep.ts
packages/api/utils/errors.ts
packages/api/utils/response.ts

- Added reusable instances of `ErrorResponse` for use across functions to new `errors` module
- Applied same to `createFundingStep` function
Ticket: AT-6409

Add reusable instances of ErrorResponse for use across functions

---

infrastructure/lib/atat-web-api-stack.ts
packages/api/taskOrderFiles/deleteTaskOrderFile.ts

Ticket: AT-6418
There is no way to check if an object has been deleted with a single `DeleteObjectCommand`. This means we will need to make a `GetObjectCommand` or  `HeadObjectCommand` to check if it exists as part of the function. 
[HeadObjectCommand docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/classes/headobjectcommand.html)
However, this solution is a problem because S3 has eventually consistent deletes, and a `GetObjectCommand` or  `HeadObjectCommand` may return a false positive.
A solution with versioning may be viable if we rework how we are creating the S3 bucket, but for now this PR only deletes the object in the bucket and **does not** check if it exists before doing so.

Implement 'deleteTaskOrderFile` function

---

atat_provisioning_wizard_api.yaml

Add missing 404 status to POST `/portfolioDrafts/{portfolioDraftId}/application`
@hannahposeyscholl-ccpo Noted this was missing in the ticket.
Ticket: AT-6467

Add missing 404 status to POST for ApplicationStep

---

atat_provisioning_wizard_api.yaml

This updates the example data to remove a mistaken property named `description`.  Also removes stray space chars.
Schema `FileMetadata` contains no property `description`.
FileMetadata combines model definitions for both subschemas `BaseObject` (:504) and `FileMetadataSummary` (:505)
This yields a property list: `id`, `created_at`, `updated_at`, `id` (repeated), `name`, `size`, `status`
This was likely a misinterpretation of the description for property `task_order_file` (:563) of schema `FundingStep`.

Update 'FundingStepEx' to remove description

---

infrastructure/lib/atat-web-api-stack.ts
packages/api/taskOrderFiles/README.md
packages/api/taskOrderFiles/deleteTaskOrder.ts
packages/api/taskOrderFiles/uploadTaskOrder.ts

This is the approach is used for 'portfolioDrafts' functions.
I suggest API operation `getTaskOrder` be renamed `getTaskOrderMetadata`.  The current name is too easily confused with `downloadTaskOrder`.
Note that...
- we'd previously listed only three (3) of the four (4) operations in the stack definition file
- the old placeholder `getTaskOrderFiles` was clearly being conflated with `downloadTaskOrder`

Rename 'taskOrderFiles' function definitions and implementation files using OperationIds from API spec

---

atat_provisioning_wizard_api.yaml

Renames operation `getTaskOrder` to `getTaskOrderMetadata`.
This will eliminate potential confusion with operation `downloadTaskOrder`.
Updates some operation descriptions for consistency.

Rename operation 'getTaskOrder' to 'getTaskOrderMetadata'

---

infrastructure/package-lock.json
infrastructure/package.json
package-lock.json
package.json
tsconfig.json

This binds typescript to a particular minor version. Since we're using
the `strict` flag, it seems like new updates may break our code so we
should do this in a more controlled way.
In this case, we should probably come back through and reconsider
whether to be more strict in our type checking on errors but that should
be done as part of a larger error handling ticket.

Update TypeScript to 4.4.2

---

infrastructure/lib/atat-web-api-stack.ts
packages/api/models/AccessLevel.ts
packages/api/models/ApplicationStep.ts
packages/api/models/Environment.ts
packages/api/models/FileMetadata.ts
packages/api/models/Operator.ts
packages/api/models/PortfolioDraft.ts
packages/api/portfolioDrafts/application/getApplicationStep.test.ts
packages/api/portfolioDrafts/application/getApplicationStep.ts
packages/api/portfolioDrafts/funding/createFundingStep.ts
packages/api/portfolioDrafts/funding/getFundingStep.ts
packages/api/portfolioDrafts/portfolio/createPortfolioStep.ts
packages/api/portfolioDrafts/portfolio/getPortfolioStep.ts
packages/api/utils/errors.ts
packages/api/utils/validation.ts

Implements function `GetApplicationStep`
- Adds models `ApplicationStep`, `Environment`, `Operator`, `AccessLevel`
- Updates existing models `PortfolioDraft`, `FileMetadata` per the API spec
- Adds step key constants `PORTFOLIO_STEP`, `FUNDING_STEP`, `APPLICATION_STEP` to model `PortfolioDraft` so they can be referenced by functions
- Updates existing functions to reference the aforementioned step key constants
- Defines function and adds to stack
- Adds GET method to new route '/portfolioDrafts/{portfolioDraftId}/application'
- Adds unit test for function
Ticket: AT-6466

Implement function 'GetApplicationStep'

---

atat_provisioning_wizard_api.yaml

Removes array wrappers around schema objects `FundingStep` and `ApplicationStep`.
Alters `FundingStep` schema object to include a `task_orders` array.
Alters `ApplicationStep` schema object to include an `applications` array.
Adds descriptions to all `*Step` schema object definitions.
Removes properties used to [fine-tune XML output](https://swagger.io/docs/specification/data-models/representing-xml/).  Outputing JSON only.

Change API spec schema objects 'FundingStep' and 'ApplicationStep' to handle multiple task orders and applications respectively

---

packages/api/package-lock.json
packages/api/package.json

Previous version was 3.28.0. This ensures that we use the latest version
of the AWS SDK.

Bump AWS SDK to 3.29.0

---

infrastructure/bin/atat-web-api.ts
infrastructure/lib/atat-auth-stack.ts
infrastructure/lib/atat-web-api-stack.ts
infrastructure/lib/constructs/authentication.ts

On stack deletion, delete all the resources. There should not be
anything left behind at this stage of development. DynamoDB tables, S3
buckets, and Cognito User Pools will all be destroyed.

Remove all the things

---

.github/workflows/test.yml
infrastructure/bin/atat-web-api.ts
infrastructure/lib/atat-auth-stack.ts
infrastructure/package-lock.json
infrastructure/package.json

To support the UI repo's CDK stack to be able to create a User Pool
Client, we need to actually make the pool's ID available somewhere. This
does a few things:
1. Renames `TicketId` to `EnvironmentId` to support names like 'dev',
'staging', or 'prod' more clearly.
2. Adds the SSM parameter for the User Pool ID with a
good-enough-for-now naming convention until we have time to formalize a
process for this (if that ever becomes necessary)
3. Updates existing code to use `EnvironmentId` naming

Make an SSM parameter with User Pool ID available

---

atat_provisioning_wizard_api.yaml
infrastructure/lib/atat-web-api-stack.ts
packages/api/models/ProvisioningStatus.ts
packages/api/portfolioDrafts/portfolio/createPortfolioStep.test.ts
packages/api/portfolioDrafts/submit/submitPortfolioDraft.test.ts
packages/api/portfolioDrafts/submit/submitPortfolioDraft.ts
packages/api/utils/errors.ts

Implement SubmitPortfolioDraft function, which _currently_ adds a `submit_id` to an existing portfolioDraft.
It returns `202 Accepted` along with the entire PortfolioDraft (this may need to be changed).
The ACs aren't especially clear if the response is an empty body, or the entire portfolioDraft.
[AT-6494](https://ccpo.atlassian.net/browse/AT-6494)

Implement function 'SubmitPortfolioDraft'

---

packages/api/models/Error.ts
packages/api/portfolioDrafts/application/getApplicationStep.test.ts
packages/api/portfolioDrafts/application/getApplicationStep.ts
packages/api/portfolioDrafts/deletePortfolioDraft.ts
packages/api/portfolioDrafts/getPortfolioDraft.ts
packages/api/portfolioDrafts/getPortfolioDrafts.ts
packages/api/portfolioDrafts/portfolio/createPortfolioStep.test.ts
packages/api/portfolioDrafts/portfolio/createPortfolioStep.ts
packages/api/taskOrderFiles/deleteTaskOrder.ts
packages/api/taskOrderFiles/uploadTaskOrder.ts
packages/api/utils/errors.ts
packages/api/utils/response.test.ts
packages/api/utils/response.ts

Using the INVALID_INPUT error code is supposed to be an indication that
the response is an actual ValidationError response. Unfortunately, we
have seen it used incorrectly for any time a 4xx error is being returned
and this has been inconsistent.
This introduces a change to the `utils/response.ts` to ensure that the
only time that INVALID_INPUT responses can be issued is by creating a
ValidationErrorResponse object and providing the error map and a
message. For all other error responses, OTHER will be used as is correct
per the API spec.

Avoid invalid uses of INVALID_INPUT

---

infrastructure/bin/atat-web-api.ts
infrastructure/jest.config.js
infrastructure/lib/atat-auth-stack.ts
infrastructure/lib/util.test.ts
infrastructure/lib/util.ts
infrastructure/package.json

There are some places (like stack names) where the title-case variant of
the environment name looks and is best; however, there are some
scenarios where we need a lowercase identifier as well.
This gives us a consistent way to handle environment names and moves all
of that logic to the app level so that it is not happening in individual
stacks and constructs. Previously, we would have had problems if an
environment ID with special characters was entered but that is no longer
an issue.
Currently, we are only passing the environment ID anywhere and it is
only to one stack. The Environment Name is purely used for
CloudFormation stack names. Both are still declared and initialized so
that we can pass them in Prop structs in the future as needed. Similar
code will need to be added to the UI …

Normalize environment names and IDs

---

packages/api/package-lock.json
packages/api/package.json

This updates the AWS SDK from 3.30.0 to 3.31.0. Due to upstream
packaging changes, we no longer need to depend on `@aws-sdk/util-dynamodb`
directly. It was previously incorrectly a peer dependency of
`@aws-sdk/lib-dynamodb`; however, it has been corrected to be a regular
production dependency. For more information, see the
[release notes](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.31.0).

Bump AWS SDK to 3.31.0

---

packages/api/models/FundingStep.ts
packages/api/portfolioDrafts/funding/createFundingStep.test.ts
packages/api/portfolioDrafts/funding/createFundingStep.ts
packages/api/utils/validation.test.ts
packages/api/utils/validation.ts

Adds checking for invalid Clin Numbers and Funding Amounts (Total Clin Value and Obligated Funds), including unit tests
Adds `isClinNumber()` and `isFundingAmount()` to validation module. including unit tests
Replaced two specific Funding Step validation messages (`TOTAL_GT_ZERO`, `OBLIGATED_GT_ZERO`) with the more general `INVALID_FUNDING_AMOUNT`
Ticket: AT-6409

Add checking for invalid Clin Numbers and Funding Amounts

---

atat_provisioning_wizard_api.yaml
infrastructure/lib/atat-web-api-stack.ts
packages/api/models/Application.ts
packages/api/models/ApplicationStep.ts
packages/api/package.json
packages/api/portfolioDrafts/application/commonMockData.ts
packages/api/portfolioDrafts/application/createApplicationStep.test.ts
packages/api/portfolioDrafts/application/createApplicationStep.ts
packages/api/portfolioDrafts/application/getApplicationStep.test.ts
packages/api/utils/validation.test.ts
packages/api/utils/validation.ts

Change model `ApplicationStep` to contain array _applications_
Add model `Application`
Relocate and organize mock data into a common location `application/commonMockData.ts `
- includes valid objects with good data (above demarcation)
- includes invalid objects with missing fields and bad data (below demarcation)
Change references in unit tests for GET function to use common mock data
- remove tests for `ErrorCode.OTHER` due to recent error response improvements in e51344485bbab60be35f3e665f0299e6c4ca1314 and 9497c9b422933bdece3b424e4a9dbbc9e5fc45c6
Apply TDD and lessons from unit testing funding step to function impl and unit tests
Decompose input validation functions for increased testability
Add unit tests for individual input validation
Define enum for validation messages in …

Implement 'CreateApplicationStep' function

---

infrastructure/lib/atat-auth-stack.ts

This is required because the UI repo's stack needs to be able to query
the list of IdPs so that the Cognito User Pool Client can configure them
as the supported IdPs.
This will unblock AT-6532.

Share the names of the created IdPs in SSM

---

packages/api/utils/response.test.ts
packages/api/utils/response.ts

In the long-term, we need a more complete solution here. And this may
not necessarily be enough. But we're going to want to limit the actual
origins that can interact with ATAT (it should not be \*); however, today
it could be any number of sandbox, local, or "real" environments with
different names so we don't have a true static list of allowed
environments nor a convenient way to dynamically build a list. The
Access-Control-Allow-Origin header also _only_ accepts "none", "*", or a
single origin so we'd need some logic to handle dynamically setting the
header based on the `Origin` header.
We probably want to look into a pattern where this is built based on a
reaction to the event. Or we even want to see if we can push this down
into the API Spec document.
This is added as an inline …

Add CORS workaround

---

infrastructure/lib/atat-web-api-stack.ts
infrastructure/lib/constructs/api-s3-function.ts
infrastructure/lib/constructs/compliant-resources.ts
infrastructure/lib/constructs/task-order-lifecycle.ts

Refactor and replace `PrivateBucket` with `SecureBucket`. 
- Enable server access logs on both source and target buckets
- Suppress cdk-nag for target bucket
- All buckets NIST SP 800-53 compliant
Ticket: AT-6557

Enable server access logs for S3 buckets

---

.github/workflows/test.yml
infrastructure/bin/atat-web-api.ts
infrastructure/lib/atat-iam-stack.ts
infrastructure/package-lock.json
infrastructure/package.json

This creates three new roles intended to be used by humans:
1. `AtatQa` for QA/Testing
2. `AtatSecurityAuditor` for Security Auditors
3. `AtatDeveloper` for Developers
This also creates one new role to be passed by developers to CloudFormation
using the `--role-arn` or equivalent flag when building using the CDK:
1. `AtatCloudFormation`
Access is currently granted to the three job function roles to the
entire Central/Management account in AWS Organizations. Long-term, that
is not a good idea and we should find a way to lock it down a bit but
right now this gives us two significant benefits:
1. Any user can assume any job role and see what those users see,
which will be especially helpful for developers to help other roles
troubleshoot other roles' IAM
2. It simplifies the configuration …

Add IAM permissions for each role

---

infrastructure/lib/atat-web-api-stack.ts
infrastructure/lib/constructs/compliant-resources.ts

This is only temporary for dev purposes to ensure that deployed
buckets can be destroyed after the completion of tickets.
Ticket: AT-6557

Update buckets removal policy

---

infrastructure/lib/atat-web-api-stack.ts
infrastructure/lib/constructs/compliant-resources.ts

Create PITRTable construct that defaults to having point-in-time
recovery (PITR) enabled for NIST SP 800-53 controls.
Ticket: AT-6555

Add table construct with PITR enabled

---

packages/api/portfolioDrafts/portfolio/createPortfolioStep.ts
packages/api/utils/errors.ts
packages/api/utils/handler.ts
packages/api/utils/response.ts
packages/api/utils/validation.ts

⚠️This PR exists as an easy diff to @zachclark-ccpo's branch⚠️
This moves the initial setup logic into it's own generic set of handlers. A lot of this was kept purely in the `createPortfolioStep` file just because I was lazy while writing. Maybe this exposes a possible path for additional refactoring? The `SetupResult` type is somewhat inspired by Rust's `Result` enum but doesn't quite replicate that functionality.
This probably breaks `isValidJson` literally everywhere else, but having the validators return valid objects feels cool. I mean, checking for `undefined` isn't much different than checking for `False`. 
Oh and `baseHandler` tries to make sure literally everything that we don't handle explicitly implicitly gets cleanly handled with a 500. We really, really, really never want to …

Make handler setup more generic

---

infrastructure/lib/atat-web-api-stack.ts
infrastructure/lib/constructs/compliant-resources.ts

Create SecureAPIGateway construct with encrypted cache and
execution logging enabled by default for NIST SP 800-53.
Replace apigateway with SecureAPIGateway to remove cdk-nag errors.
Ticket: AT-6556

Enable API Gateway Cache & Execution Logging

---

atat_provisioning_wizard_api.yaml

If we always create the security scheme objects (without the Fn::If),
then the API still returns a 401 Unauthorized response when a token
isn't provided. If we exclude it entirely, then we're able get a 200.

Conditionally create the securityScheme

---

atat_provisioning_wizard_api.yaml
packages/api/models/PortfolioStep.ts
packages/api/models/TaskOrder.ts
packages/api/models/TypeFields.test.ts
packages/api/portfolioDrafts/funding/createFundingStep.test.ts
packages/api/portfolioDrafts/getPortfolioDraft.test.ts
packages/api/portfolioDrafts/portfolio/createPortfolioStep.test.ts
packages/api/utils/validation.test.ts
packages/api/utils/validation.ts

The UI design has evolved and this is closing the gap in the API.
- Updates API spec to move CSP property to Portfolio Step from Funding Step
- Updates API spec examples
- Updates models `TaskOrder` (part of `FundingStep`) and `PortfolioStep`
- Updates impacted unit tests
Ticket: AT-6677

Move CSP data to Portfolio Step

---

atat_provisioning_wizard_api.yaml
packages/api/utils/response.ts

This ensures that all responses have the CORS headers included as well as adding an `OPTIONS` route for request pre-flighting. For now, we allow the `*` origin so that we can have different frontends point to the app; however, we will eventually need to lock this down to a trusted origin.
See https://docs.aws.amazon.com/apigateway/latest/developerguide/enable-cors-for-resource-using-swagger-importer-tool.html for more information on this implementation.

Add consistent CORS support

---

infrastructure/lib/atat-web-api-stack.ts

This will allow multiple stacks to be deployed side-by-side in the same
environment (as we do in Sandbox). Queue names are unique.
This is a fixup to #270.

Don't hardcode the queue name

---

packages/cognito/preTokenGeneration/groups.ts

This was picked up by SonarCloud as a potential issue. The regex matches
one of the known problematic patterns. Replacing the regex with a
split-then-trim actually makes the intent of the code more clear anyway.

Replace a less-than-optimal regex

---

infrastructure/lib/constructs/authentication.ts

Because the user pool theoretically could have a static user created,
this enforces strict MFA and password requirements on the pool to ensure
that if a user is for some reason created that the password policy in
place is a strict as possible.

Create MFA and Password Policies for UserPool

---

infrastructure/package-lock.json
infrastructure/package.json

This contains fixes for the bug we were experiencing that caused
failures on parsing intrinsic functions. Dependabot would likely have
opened this later today but I'm tracking this now so it felt just as
easy to open the PR.

Update cdk-nag to 0.0.119

---

.github/workflows/test.yml

Technically, SonarCloud does not support external PRs:
- https://portal.productboard.com/sonarsource/1-sonarcloud/c/50-sonarcloud-analyzes-external-pull-request
- https://jira.sonarsource.com/browse/MMF-1371
We are intentionally skipping the SonarCloud step for Dependabot (which are external) PRs.

Run SonarCloud under pull_request context

---

infrastructure/bin/atat-web-api.ts
infrastructure/lib/aspects/removal-policy.ts
infrastructure/lib/atat-web-api-stack.ts
infrastructure/lib/util.test.ts
infrastructure/lib/util.ts

Currently, disjoint mechanisms are used to set the removal policy for
constructs across the application. This uses an Aspect to consistently
apply a removal policy whenever we're dealing with a sandbox
environment. For resources in more permanent environments, the default
retention policies are used. In general, the defaults are generally to
retain resources that hold data such as S3 buckets, DynamoDB tables, and
OpenSearch Domains; however, we need to delete those in our Sandbox
environments. This ensures the proper policy is applied to all resources
in those sandboxes while leaving the default for dev/staging/prod, etc.
While this does now special case "dev", "staging", and "prod", which I
am not a fan of, it resolves the issue of "dev" currently having removal
policies set to DESTROY …

Use an Aspect to set Removal Policy

---

packages/api/portfolioDrafts/application/createApplicationStep.test.ts
packages/api/portfolioDrafts/application/createApplicationStep.ts

Remove admin role business rule validation to allow UI to submit
the `applicationStep` with no operators in Step 3. The operators are
added in Step 4 and a new endpoint will be added that will add
add back in the admin role business rules for when Step 4 is
submitted.
This reverts only the business rules for the admin operators done 
in Ticket: AT-6723

Revert admin role business rule

---

infrastructure/lib/atat-web-api-stack.ts

This makes it so it can be retrieved in other places without guessing
the correct domain based on environment ID (which is fragile).

Expose Cognito Domain value via SSM

---

infrastructure/lib/atat-iam-stack.ts

This is necessary to create the front-end resources because we don't
want two Providers for the same issuer.
Ticket: AT-6847

Add OIDC Provider export

---

.gitignore

Add file `ormconfig.json` to `.gitignore`
This file is for configuration of typeorm for local development.
Reference: https://typeorm.io/#/using-ormconfig/using-ormconfigjson

Add local typeorm config to gitignore

---

packages/api/package-lock.json
packages/api/package.json
packages/email/package-lock.json
packages/email/package.json
packages/rds/package-lock.json
packages/rds/package.json

This bumps all packages to the newest version possible. For most clients
this is 3.43.0; for some supporting/util packages, this is 3.41.0 or
3.40.0. Additionally, the unused `@aws-sdk/credential-providers` package
was removed from `atat-web-api-rds`.
Hopefully this will unstick dependabot.

Update AWS SDK JS v3 dependencies

---

packages/api/portfolioDrafts/createPortfolioDraft.ts

This causes performance issues on the first request that result in
persistent 500s. This removes the bottleneck to prevent this from being
an issue in the live dev environment.
A separate test route eventually will be created to support testing the
database interactions in a subsequent PR.

Remove database connection from /portfolioDrafts

---

infrastructure/lib/atat-web-api-stack.ts
packages/api/dbTest.ts
packages/api/portfolioDrafts/createPortfolioDraft.ts

We previously used `POST /portfolioDrafts` for this but that caused
problems because it was used by the UI directly so if there were issues
with talking to the database, we took down the app. This lets us test
them somewhere outside the actual app code.

Add database test route

---

atat_internal_api.yaml

The CSP Provisioning process will be executed roughly as follows:
1. User interacts with ATAT UI / Internal API to update ATAT resources (Portfolios, Applications, Environments & Task Orders)
2. When ready, User submits all pending resources for provisioning. Pending resources are defined as new rows in the database whose status is not `COMPLETE` or `IN_PROGRESS`
3. The POST /portfolios/:idsubmit Lambda walks the tree of the given Portfolio and creates one or more `CspInvocation` objects and passing each to their own instance of a Step Function workflow
4. The  CSP Invocation Lambda reads the given `CspInvocation` object and makes a matching invocation to the endpoint contained within it (initial implementation in Phase 1 will be totally mocked out, but include ability to test all paths) …

Added  CspInvocation and CspResponse objects

---

packages/cognito/preTokenGeneration/groups.test.ts
packages/cognito/preTokenGeneration/groups.ts

If there is not a claim for groups or if we have the wrong key, rather
than failing to generate a token at all, we should just return an empty
list of groups.
To make logs somewhat easier to query in CloudWatch, I've made them
semi-structured. Clearly we still need to decide our logging framework
but I wanted to play with this for now.
This avoids an issue we're experiencing with a recently-added IdP that
either is not providing a groups attribute or the attribute name is
different than what we expect.

Return an empty group list when unable to parse

---

packages/cognito/preTokenGeneration/groups.ts

Added console log to pretoken event as a temporary means of debugging GD integration (specifically, group mapping).
Ticket: AT-6874

AT-6874: Added temporary logging for debugging GD integration 

---

packages/api/dbTest.ts

Previously query results were not logged and `result` appeared to be empty when function returned status 200.
This change logs query results as expected.

Fix logged output of DbTest lambda function

---

infrastructure/lib/atat-web-api-stack.ts
packages/api/utils/database.ts
packages/orm/entity/Application.ts
packages/orm/entity/Clin.ts
packages/orm/entity/Environment.ts
packages/orm/entity/Portfolio.ts
packages/orm/entity/TaskOrder.ts

This PR fixes a few common errors that were seen across the team and implements the changes that fixes those errors (RDS endpoints implementation).
- Add `logGroupName` for the state machine in the stack and use the prefix `/aws/vendedlogs/states/` to over come the `Invalid Logging Configuration: The CloudWatch Logs Resource Policy size was exceeded.` when trying to `cdk deploy`.
- Add entities classes for the connection configuration to prevent `EntityMetadataNotFoundError`.
- Add column types to entities to prevent `CloumnTypeUndefinedError`.

Fix Step Functions LogGroup Error and other database errors

---

infrastructure/lib/atat-web-api-stack.ts
infrastructure/lib/constructs/lambda-fn.ts
infrastructure/lib/queue-permissions.ts
infrastructure/lib/resource-permissions.ts
infrastructure/lib/table-permissions.ts

There were errors during file upload due to a missing S3 bucket name
parameter. This ensures that is added by setting permissions between the
function(s) and the bucket.

Fix 500 errors on file upload

---

atat_internal_api.yaml
infrastructure/lib/atat-web-api-stack.ts
packages/api/portfolios/environments/createEnvironment.test.ts
packages/api/portfolios/environments/createEnvironment.ts
packages/api/portfolios/environments/updateEnvironment.test.ts
packages/api/portfolios/environments/updateEnvironment.ts
packages/api/repository/EnvironmentRepository.ts
packages/api/utils/businessRulesValidation.test.ts
packages/api/utils/businessRulesValidation.ts
packages/api/utils/errorHandlingMiddleware.ts

Implement `PUT /portfolios/:portfolioId/applications/:applicationId/environments/:environmentId`
Add `updateEnvironment` operation to completely replace an environment by id 
(internal api - RDS endpoint) with tests only for local development to ensure the 
expected behavior.
Connect function with infrastructure.
Ticket: AT-6893

Implement updateEnvironment func (RDS endpoint)

---

.github/CODEOWNERS
.github/workflows/test.yml
.pre-commit-config.yaml
.secrets.baseline

This adds base secret scanning capabilities using the
`Yelp/detect-secrets` project which we've used before. For now, a
`.pre-commit-config.yaml` is added which we will require using as part
of AT-7100 (but it's added now for convenience and to demonstrate that
the selected secret scanning tool works with pre-commit).
Going forward, secrets can be added to the `.secrets.baseline` file;
however, modifying that file requires review from a member of the
`@dod-ccpo/atat-code-maintainers` team.
Additionally secrets going forward can be added to the allowlist in the
baseline file by running detect-secrets scan.
Ticket: AT-7099

Add secret scanning with `detect-secrets`

---

.github/workflows/test.yml
.gitignore
.secrets.baseline
README.md
bin/atat-base-infra.ts
lib/aspects/removal-policy.ts
lib/atat-iam-stack.ts
lib/util.ts
test/util.test.ts

The main changes to actually add the necessary permissions are in
`lib/atat-iam-stack.ts`. The remaining changes are simply adding
additional support code to make it easier to manage the deployments.
Eventually (but soon) we probably want to talk about identifying a path
to removing the `atat:EnvironmentId` context value as a requirement for
deploying the base infrastructure (since we really only want there to be
one per _account_ not per environment; and in some cases
account:environment may either be 1:1 or 1:N).

Update IAM configuration to work with CDKv2 roles

---

lib/atat-web-api-stack.ts
lib/constructs/apigateway.ts
lib/http.ts

This creates a basic policy to allow users to access the gateway at
specified routes on specified methods (one could allow "*" on "/*"). It
also creates a basic permissions boundary to ensure that the created
users cannot do anything beyond executing the API.
Ticket: AT-7075

Add basic policy for IAM users using the gateway

---

.secrets.baseline
lib/atat-iam-stack.ts
sonar-project.properties
test/apigateway.test.ts
test/atat-iam.test.ts

This PR involves creating additional unit tests to verify that the CloudFormation templates generated by CDK meet our expectations.
This included writing fine-grained assertions to test specific stacks (`atat-iam-stack`, `atat-net-stack`, and `atat-web-api-stack`)
Official CDK v2 documentation: https://docs.aws.amazon.com/cdk/v2/guide/testing.html

Create additional CDK unit tests

---

utils/aws-sdk/sqs.ts
utils/aws-sdk/step-functions.ts

The FIPS-compliant endpoints in the AWS SDK's `endpoints.json` file have
been updated to properly reflect the correct hostname.

Use FIPS endpoints for all AWS APIs

---

.secrets.baseline
lib/atat-iam-stack.ts
lib/atat-iam.test.ts
lib/atat-web-api-stack.ts
lib/constructs/apigateway.ts
package-lock.json
package.json

The [`iam-floyd`](https://github.com/udondan/iam-floyd) package provides
a fluent builder-like interface for create IAM policies. This gives them
a more human-readable format as well as nice abstractions for certain
things (like `ifEncrypted()`). This and the `ifX` methods make it a bit
easier to naturally attach conditions to IAM policies. In the end, we
still get an `iam.PolicyStatement` object (through the `cdk-iam-floyd`
package) which the CDK can naturally turn into JSON/CloudFormation.

Use the iam-floyd library for IAM policy creation

---

lib/atat-web-api-stack.ts

Update the name of the provisioning job resource to match the specification `/provisioning-jobs`.
Ticket: AT-7078

Update API Gateway provisioning resource name

---

cdk.json

This couldn't be included in the initial PR because the pipeline was
already deployed and watching the feature branch. Had it switched to
watching develop before the pipeline was merged all sorts of wonkiness
could have occurred and I didn't really want to clean that up. This just
switches the default.

Make pipeline track `develop` by default

---

.github/workflows/test.yml

The default the [permissions on the GitHub token][1] grant a lot more
access than is actually required as part of this workflow, especially
for PRs that originate from within this repository. Because the
`GITHUB_TOKEN` is accessible not only via `secrets.GITHUB_TOKEN` but
also on the context object as `github.token`, theoretically, other
actions in use could access the secret. Limiting the permissions is a
good idea.
[1]: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

Only give the PR test workflow read access

---

lib/atat-iam-stack.ts
lib/atat-net-stack.ts

This gives developers the ability to read and poke in the Lambda and API
Gateway consoles, permissions that may have been missing before. This
doesn't grant everything (and definitely not permission to invoke
anything) but hopefully it makes life a little easier.

Make using the console easier

---

lib/atat-net-stack.ts
lib/constructs/apigateway.ts
lib/constructs/provisioning-sfn-workflow.ts

Right now most of our logs are AWS Lambda function logs, which have
their logs groups created automatically. Those log groups have
indefinite retention specified. Our other log groups use different
configurations and we should just make everything consistent until we
really solidify how long we plan on retaining for.

Configure logs for indefinite retention

---

.github/workflows/test.yml
bin/app.test.ts
bin/app.ts
bin/atat-web-api.ts
cdk.json
lib/atat-pipeline-stack.ts

This PR satisfies AT-7448 by adding a `VpcCidr` context parameter to our CDK config. This parameter has the following rules:
1. If the given Environment is a Sandbox, `VpcCidr` must NOT be defined.
2.If the given Environment is NOT a Sandbox, `VpcCidr` must be a valid CIDR block such as `10.100.0.0/20`.
I also moved the majority of the logic out of `bin/atat-web-api.ts` to `bin/app.ts` so that we could unit test it without invoking `app.synth()`. In doing so I changed the `process.exit()` calls to throw Errors instead. I added a number of test cases for input validation but did not include any CDK level validations (e.g. of generated CloudFormation templates).

Support configurable CIDR blocks

---

hoth_api.yaml

This is the schema used for the `generateDocument` POST request.
The `DescriptionOfWork` object includes all properties needed to complete the DOW document, and separate schemas had to be
created to improve readability.
These schemas were created referencing the specific SNOW Tables needed for the DOW (See https://github.com/dod-ccpo/atat-snow/pull/48). 
[Acquisition Package Field Mapping](https://ccpo.atlassian.net/wiki/spaces/AT/pages/2282160166/Acquisition+Package+Field+Mapping) Confluence Page was used along with the actual **Draft JWCC Description of Work Template** (See slack comment for link).
In total this PR adds the following schema:
1. `DescriptionOfWork`
2. `CurrentEnvironment`
3. `EnvironmentInstance`
4. `ClassificationLevel`
5. `StorageUnit`
6. `PerformanceRequirements`
7. …

Define DescriptionOfWork schema (and supporting schema) in HOTH API

---

.pre-commit-config.yaml

For some team members, running `npm run lint` is remarkably slow (on the
order of minutes) when run across the full codebase. Because most
developers have ESLint run as part of the save process in their IDEs and
because we catch problems with linting in the CI pipeline; we can safely
remove it from the pre-commit configuration and be sure that unlinted
code does not make it to the `develop` branch. Once we've resolved
issues with linting being slow, we can potentially add this back.

Remove linting from pre-commit

---

hoth_api.yaml

There were several uncaught DOW schema incompatibilities, this PR's intention is to fix those problems and refine the schema to better serve the `generateDocument` API.
See the following comments for the reason for the changes:
https://github.com/dod-ccpo/atat-snow/pull/67#issuecomment-1139022297
https://github.com/dod-ccpo/atat-snow/pull/67#issuecomment-1139043489
`required_training_services` is now an array of training courses, to
better reflect the expected SNOW input
Remove `task_order_number`, this field is completed by the KO and
isn't required to be passed to the DOW

DOW Schema Improvements

---

.secrets.baseline
lib/atat-web-api-stack.ts
lib/constructs/provisioning-sfn-workflow.ts
lib/constructs/sqs.test.ts
lib/constructs/sqs.ts

Create new `Queue` construct.
Add two queues to the atat-web-api-stack
- `costRequestQueue`
- `costResponseQueue`
- add unit test for queue
Update the provisioning queue to use new `Queue` construct.
Ticket: AT-7453

Add two cost queues to infrastructure

---

hoth_api.yaml

This PR simply defines the schema to be used in other tickets. Ended up re-using `CspResponse` rather than recreating the wheel for `CostResponse`.

AT-7454: Added CostRequest & CostResponse schema objects

---

lib/atat-web-api-stack.ts

Add `puppeteer-core` as dependency in the bundling of the generate
document lambda, due to the below error. The error causes the
`ATAT Generate Description of Work` subflow to error.
```
Cannot find module 'puppeteer-core/lib/cjs/puppeteer/common/Browser.js'
```
**Note:** This was not included previously, because it did not appear to be required and worked in sandbox without the addition of `puppeteer-core` being bundled.

Bundle puppeteer-core with the generate-document fn

---

.secrets.baseline
README.md
api/cost/consume-cost-response.ts
api/cost/start-cost-job.test.ts
api/cost/start-cost-job.ts
api/provision/consume-provisioning-job.ts
api/util/queueConsumer.test.ts
api/util/queueConsumer.ts
hoth_api.yaml
lib/atat-web-api-stack.ts
lib/constructs/api-route.ts
lib/constructs/cost-api-implementation.test.ts
lib/constructs/cost-api-implementation.ts
models/cost-jobs.ts
tsconfig.json
utils/middleware/common.ts
utils/middleware/error-handling-middleware.ts
utils/middleware/ip-logging.ts
utils/middleware/xss-sanitizer.ts

Added /cost-jobs resource + GET and POST routes
Tweaked middleware slightly to make it easier to add new types
Abstracted consume-provisioning-job.ts into a generic Queue Consumer class and used it to create consume-cost-response.ts.
Ticket: AT-7628

AT-7628: Adding proxy routes to enqueue cost API requests and dequeue responses

---

lib/atat-iam-stack.ts

The `Conditions` should not be a list (oops). This was added/broken in
PR #929; however, this was not noticed until #977.

Fix breakage in IAM deployment

---

api/cost/cost-request-fn.test.ts
api/cost/cost-request-fn.ts
api/cost/start-cost-job.test.ts
api/provision/consume-provisioning-job.test.ts
api/provision/csp-configuration.test.ts
api/provision/csp-write-portfolio.test.ts
api/provision/csp-write-portfolio.ts
api/provision/result-fn.test.ts
api/provision/start-provisioning-job.test.ts
api/util/common-test-fixtures.ts
api/util/csp-request.test.ts
api/util/csp-request.ts
document-generation/generate-document.test.ts
hoth_api.yaml
lib/atat-web-api-stack.ts
lib/constructs/api-route.ts
lib/constructs/cost-api-implementation.test.ts
lib/constructs/cost-api-implementation.ts
models/cost-jobs.ts
models/provisioning-jobs.ts
utils/middleware/error-handling-middleware.ts

Implement cost invocation function to make external CSP request for cost data. 
Create `cost-request-fn` that makes a CSP request
- add `costRequestFn` to `cost-api-implementation` (infrastructure)
- add secrets and grant permissions for making requests
- consumes messages from `CostRequestQueue` as an event source
- send messages to `CostResponseQueue`
- extract `makeARealRequest` into `cspRequest` for reuse
- remove `makeARealRequest`
- Add unit tests
- functions `cost-request-fn` and `csp-request`
- infrastructure `cost-api-implementation`
Ticket: AT-7457

Implement CostRequest function

---

lib/constructs/cost-api-implementation.ts
lib/constructs/provisioning-sfn-workflow.ts
lib/constructs/sfn-lambda-invoke-task.ts
lib/constructs/sqs.test.ts
lib/constructs/sqs.ts
lib/constructs/state-machine.ts

This refactors a pretty significant chunk of constructs within the
application to just directly extend other components rather than build
compositions based on them. For a few things, we're basically just
creating pre-configured variants of another construct type (SQS Queue,
State Machine, etc) and we can handle that pretty trivially and remove
some need to make wonky `.foo` attribute accesses. This also makes them
easier to just pass around within the CDK app.
Notably, the API Gateway REST API is not refactored. That adds a few
methods and my worry there is that we actually use some names that may
eventually conflict with the underlying resource (not likely but
possible) and so I kinda tried to avoid that.
Because the `SfnLambdaInvokeTask` was only ever created in one place, we
can also …

Refactor CDK constructs

---

utils/aws-sdk/secrets-manager.ts

The bulk of the issue is described in the code comment. Putting this
explanation inline makes it more immediately clear to future
maintainers, reviewers, or auditors why we've omitted the flag in this
particular case.
All other services we invoke from within our VPC use the same hostname
for FIPS and non-FIPS so keeping `useFipsEndpoint` is fine for those
(SQS and Step Functions).

Fix networking issues with AWS Secrets Manager

---

bin/app.ts
cdk.json
lib/atat-notification-stack.test.ts
lib/atat-notification-stack.ts
lib/atat-pipeline-stack.ts

Similar to the currently-open monitoring PR, this adds a base for
setting up notifications everywhere except our sandbox account. These
notifications are required under the STIGs and help ensure we meet some
requirements under 800-53.
We ignore Sandbox because we build IAM stuff there all the day and we'll
never see a real email; it'd just be notifications.

Add required notifications to be sent via email

---

lib/atat-net-stack.ts
lib/atat-net.test.ts

This also disables VPC DNS Query Logs for now until we work out some IAM
and resource policy issues.

Update Security Group rules for API Gateway

---

hoth_api.yaml

Add the IGCE schema to support document generation of the IGCE document.
Summary of the information that needs to be captured is below. See [ticket comment](https://ccpo.atlassian.net/browse/AT-7757?focusedCommentId=337288) for a more in depth explanation of the IGCE document and an example with filled in data. 
There are multiple period sheets that contain information for each period. The information required: 
- a `period of performance` - an amount of time (e.g., 6 months)
- the `funding document number` - relates to the funding plan
- is either the GTC and order number when using G-Invoicing and the 7600 A/B documents, OR the MIPR number when using a MIPR document. 
- one or more `CLIN line items` (various properties)
Most of the summary sheet will be filled in based upon formulas …

Update HOTH specification with IGCE schema

---

.github/workflows/test.yml
.secrets.baseline
lib/atat-pipeline-stack.ts
lib/atat-web-api-stack.ts
lib/constructs/apigateway.ts
lib/constructs/provisioning-sfn-workflow.ts
lib/constructs/vpc-endpoint-lb-target.ts

We still need to do some work to solve IAM and Network; however, this
fixes the issues in the main app stack. All remaining issues are
resolved or are suppressed and the check is added to the deployment
pipeline to ensure that we always remain compliant. This is far easier
to do now that we have networking solved (except that tricky
`AwsCustomResource`).
This also adds a synthesis of a full environment to our CI workflow.

Resolve or supress all 800-53r4 checks in ATAT stack

---

.secrets.baseline
lib/atat-web-api-stack.ts

This is a missing feature in CloudFormation in us-gov-west-1. Coordinate
internally for questions about the status of the related support case.

Temporarily don't encrypt log groups

---

api/util/csp-request.ts
lib/constructs/cost-api-implementation.ts

Per the API spec, this is only permitted to read cost.

Fix allowed scopes for Cost Request Function

---

api/provision/start-provisioning-job.test.ts
api/util/common-test-fixtures.ts
hoth_api.yaml
models/provisioning-jobs.ts

Update provisioning schema and HOTH specification to account for the changes in operators 
used for provisioning jobs, which aligns with the ATAT spec  version `0.3.0`. 
- Update provisioning job model and HOTH spec
- Update tests to reflect operator changes
Ticket: AT-7804

Update provisioning schema and HOTH spec

---

document-generation/generate-document.test.ts
document-generation/generate-document.ts
document-generation/handlebarUtils/sampleTestData.ts
models/document-generation.ts
utils/errors.ts

Currently the document generation lambda supports generating the _Description of Work_ document as `PDF` with handlebars + puppeteer.  This PR allows the lambda to recognize the _IGCE_ document type and lays groundwork for the generation of an `XLSX` file (see #1105) with [ExcelJS](https://www.npmjs.com/package/exceljs).
- Requests for `IGCE` should return an HTTP 501
- Requests for `Description of Work` should continue to work as expected
Inspecting incoming document type in `baseHandler` and delegating to respective functions for generating PDF or XLSX.  Left PDF generation largely unchanged with the exception of relocating the handling of unrecognized document type (to switch default).
Added a new unit test checking for HTTP 501.  Added sample IGCE request data to use in new unit test …

Add support for IGCE to document generation lambda

---

README.md
bin/app.test.ts
bin/app.ts
docs/manual-steps.md
lib/atat-pipeline-stack.ts
lib/constructs/cost-api-implementation.ts
lib/constructs/provisioning-sfn-workflow.ts
lib/context-values.ts

This PR makes two primary modifications. First, an override context
value is added to make it easier to override the version of the GitHub
PAT secret that CloudFormation resolves to force it to pick up a new
version. Because this is handled with yet another wonky context key,
the way we handle context keys generally is also improved to be more
maintainable and understandable in the future.
In some scenarios, the PAT needs to be rotated; however, CloudFormation
will not automatically pick up that there's a new version. This is
because CloudFormation will only re-resolve the secret when either the
version changes or a property of the resource changes. I tried to do
this with Tags but that didn't seem to be sufficient.
Instead, what we do is conditionally pass a specific version ID to …

Fix GitHub PAT issue and refactor context keys

---

cfn-templates/sso-permission-sets.cf.yaml

Not all AWS accounts will necessarily have a permissions boundary. We
need to support building our permission sets in such an environment. We
can do this by conditionally providing that attribute.
To avoid awkward issues with potential default values etc, we use the
value "!" as the "policy name" that causes us to ignore applying the
permissions set. We use "!" because it is not valid in a policy name and
because passing the empty string is awkward in the CloudFormation
console and CLI.
This also turns `CentralAccountRolePermissionsBoundary` into a required
parameter instead of an optional parameter with a default value; this is
likely the better long-term decision anyway.

Support building permission sets without permissions boundary

---

api/cost/cost-request-fn.test.ts
api/provision/async-provisioning-check.test.ts
api/provision/csp-write-portfolio.test.ts
api/util/common-test-fixtures.ts
api/util/csp-request.ts
hoth_api.yaml
models/provisioning-jobs.ts

Make `portfolioId` optional in the `ProvisioningRequest` for the provisioning schemas and models.
Update `cspMockResponse` to hardcode `location`.
- Removed `uri` and `network` in unit test
- Update unit tests

Update Provisioning schema and models

---

api/client/client.ts

Previously the `$metadata.request` returned the axios `response.request`
object, which is not the request that is sent to the CSP. To fix this
the original request sent to the CSP is passed into the transformation
functions as an argument.

Fix CSP response

---

api/client/client.ts
utils/atat-client.ts

Add logging to `atat-client` to help view the external requests and responses sent to the CSP.

Add logging for ATAT CSP client

---

api/provision/async-provisioning-check.test.ts
api/provision/async-provisioning-check.ts
api/provision/csp-write-portfolio.test.ts
api/provision/csp-write-portfolio.ts
api/util/csp-request.ts
lib/constructs/provisioning-sfn-workflow.ts
models/provisioning-jobs.ts
utils/middleware/error-handling-middleware.ts

This addresses the error caused by the `targetCsp` not being available
in the `async-provisioning-check` fn to create an `atat-client` which more
than likely happened due to refactoring the `ProvisioningRequest` schema 
in https://github.com/dod-ccpo/atat-web-api/pull/1185/commits/819fdb86636796bcc0bb63532793cfe133bdaf3d#top .
As a result the `targetCsp` from the original SFN input is not available 
in messages sent to the async provisioning queue. An update to the SFN workflow 
now passes the `targetCsp` into the `result-fn` state input, which allows
the `async-provisioning-check` fn to create an `atat-client` when messages
are polled and and the `atat-client` makes a request to the target CSP.
The `targetCsp` is made optional because some functions already have
access to the `targetCsp` …

Update `result-fn` state inputs

---

api/provision/async-provisioning-check.ts

Fix bug that accounts for a mock message being sent to `async provisioning check` fn.
Appears similar to the last bug due to the `name property on undefined` but this is 
happens inside the `makeRequest()` when mocking CSPs.

Update async provisioning check fn mocking logic

---

api/provision/async-provisioning-check.test.ts
api/provision/async-provisioning-check.ts
api/provision/start-provisioning-job.ts
api/util/csp-request.ts
lib/constructs/provisioning-sfn-workflow.ts
models/provisioning-jobs.ts
utils/middleware/error-handling-middleware.ts

Create an `initialSnowRequest` property and pass along to the async provisioning queue.
All initial properties from the SNOW request are available for use such as `targetCsp` and
the `jobId`.
- Refactor SFN initial input
- Update the `async-provisioning-check` fn

Refactor SFN task inputs

---

.secrets.baseline
bin/app.ts
lib/atat-monitoring-stack.ts
lib/atat-net-stack.ts
lib/atat-pipeline-stack.ts
lib/atat-web-api-stack.ts
lib/context-values.ts

These logs will be helpful from a troubleshooting perspective as well as
required for compliance and security reasons. Enabling them requires
specifying the region on the stack. This is really unfortunate because
it means that our template isn't 100% portable anymore (as in, an
already-built template can no longer be run in any region; though, we
can still build a template that works in any region). The change is a
bit unfortunate as it requires _all_ synthesis to take place with the
`AWS_PROFILE` environment variable set where it points to the desired
target account/region.

Add ELB Access Logs

---

manual-steps/stig-remediation.ts

The call to actually enable the feature was missing, we only reset the
key. Now we reset the key to the default and then we enable the setting.
This ensures that the key is one that's available prior to enabling
during bootstrapping.

Add enable call in addition to reset for EBS encryption

---

lib/atat-net-stack.ts
lib/constructs/vpc-default-sg-rule-remove.ts
lib/custom-resources/delete-default-sg-rules.ts

AWS' Best Practices for the CIS Benchmarks and for Foundational Best Practices recommend not having any rules that allow traffic in the Default Security Group for a VPC. This SG by default allows traffic within the SG and all egress traffic. We **do not** place any resources in the Security Group. Nonetheless, for some reason we are required to comply with the CIS rules 4.3 and 5.3 as well as EC2.2.
CloudFormation (and therefore the CDK) do not provide a native way to delete resources as part of resource definitions. So we have to write a custom resource to handle the deletions. This is a gross abuse of Custom Resources and perhaps a hook triggered on `AWS::EC2::VPC` creation would be better, but with this setup we can directly pass the attributes of the VPC to the custom resource to …

Add a custom resource to remove all rules from the VPC default SG

---

cfn-templates/ses-user.yaml

Wherever possible, code from AWS documentation has been reused. To
facilitate this, the handler for the custom resource is written in
Python.
Refer to:
- https://docs.aws.amazon.com/ses/latest/dg/smtp-credentials.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-responses.html

Add a template for configuring SES via an IAM user

---

document-generation/igce-document.ts
document-generation/utils/sampleTestData.ts
hoth_api.yaml
models/document-generation.ts

Modified schema to be `camelCase`, renamed several fields, and added `contractingShop` field.
Example request body:
```json
{
"fundingDocument": {
"fundingType": "FS_FORM",
"gtcNumber": "string",
"orderNumber": "string",
"miprNumber": "string"
},
"surgeCapabilities": 0,
"periodsEstimate": [
{
"period": {
"period_type": "BASE",
"period_unit_count": 0,
"period_unit": "DAY",
"option_order": 0
},
"periodLineItems": [
{
"idiqClin": "string",
"contractType": "FFP",
"dowTaskNumber": "4.2.1.1",
"serviceTitle": "Compute",
"itemDescription": "string",
"unitPrice": 0,
"quantity": 0,
"unit": "string"
}
]
}
],
"instructions": {
"estimateDescription": "string",
"assumptionsMade": "string",
"toolsUsed": "string",
"informationSource": "string",
"previousEstimateComparison": "string"
},
"contractingShop": …
```

Update IGCE JSON Schema

---

document-generation/ifp-document.test.ts
document-generation/utils/sampleTestData.ts
document-generation/utils/utils.test.ts
document-generation/utils/utils.ts

Remove GTC number. Only the Order number is needed for IFP document.

Remove GT&C number from IFP document

---

document-generation/igce-document.ts

`optionOrder` used to start on 1 for Option Period 1, but due to `optionOrder` starting on 1 for Base Period instead of null, Option Period 1 had an `optionOrder` of 2. 
This fixes that issue.
Test it on the dev PDI with `ACQ0000230`, you will see that Option Period 1 is an empty page, and all option periods are shifted over:
Test it on the At838423WebApi sandbox endpoint and you will see Option Period 1 is in its proper location:

Update optionOrder page calculation to reflect optionOrder changes

---

lib/constructs/provisioning-sfn-workflow.ts
lib/constructs/state-machine.ts

Increase state machine timeout from 10 seconds to 10 minutes.
Currently timing out when making a request to external CSP.
Additionally, increase `consume-provisioning-job` lambda timeout from 20 seconds to 1 minute.

Increase State Machine timeout

---

lib/constructs/api-sfn-function.ts
lib/constructs/sfn-lambda-invoke-task.ts

- Update tasks default timeout in the SFN to 6 minutes. This value
was selected since the longest lambda timeout in the SFN is 5
minutes and this ensures that the lambda timeout before the SFN.
- Update api-sfn-function to provide a lambda default of 5 minutes
rather than 5 seconds.

Increase SFN Task timeout

---

cdk.json
lib/constructs/identity-provider.ts

It looks like the CDK may have introduced an issue with stack updates to
the `DescribeCognitoUserPoolClient`. There is a possible unmerged patch
upstream. To unblock updates, this adds a temporary workaround
(reimplemented the custom resource internally) until the fix (or an
alternative) is merged.

Add workaround for issues with stack updates

---

document-generation/chromium.ts
package-lock.json
package.json

Update `puppeteer-core@19.6.0` and `@sparticuz/chromium@110`.
Document generation for PDFs is no longer being used at the moment, 
so we might want to consider if the puppeteer dependencies can be removed.

Update puppeteer to v19.6.0

---

document-generation/igce-document.ts
document-generation/utils/sampleTestData.ts
models/document-generation.ts

Added support for Contracting Shop on the Igce Summary Page.
Ditco Fee Calculation: `=K24 *.0225`
(This is unchanged)
Contracting Shop Fee Calculation `const fee = (payload.contractingShop.fee / 100).toFixed(2); // round to 2 decimal places`
This uses the contracting shop fee, which exists on the Requirements Cost Estimates Table (how_est_dev_contracting_office_other_charges_fee).

Add support for Contracting Shop Fee on Igce Summary Page

---

api/client/client.test.ts
api/client/client.ts
api/provision/csp-create-environment.test.ts
api/util/common-test-fixtures.ts

- Fixed version number header
- Updated client.ts to encode path parameters (not entire URL or path portion)

AT-8895: HOTH API: Encode path parameters in CSP requests and update version number header to remove "v"

---

hoth_api.yaml

- Fixes a reference that was missed when we renamed `OperatorPayload` to `AdministratorPayload` in the HOTH API

HOTH API: Fix reference to AdministratorPayload

---

.secrets.baseline
cfn-templates/sso-permission-sets.cf.yaml

Change will allow testing to see logs

Update IAM: Give QA Read-only access to CloudWatch logs

---

document-generation/igce-document.ts

Replaces static DITCO fee percentage in IGCE docgen.  Follow on PR due to DITCO fee percentage now being included in IGCE payload.
Reference https://github.com/dod-ccpo/atat-snow/pull/347#discussion_r1170649648

Replace static DITCO fee percentage in docgen with IGCE payload reference

---

document-generation/dow-document.test.ts
document-generation/eval-memo-document.test.ts
document-generation/eval-memo-document.ts
document-generation/generate-document.test.ts
document-generation/generate-document.ts
document-generation/igce-document.test.ts
document-generation/justification-and-approval-document.test.ts
document-generation/mrr-document.test.ts
document-generation/utils/sampleTestData.ts
models/document-generation.ts
models/document-generation/evaluation-memo.ts

- Adds and makes use of interface `IEvaluationMemo`
- Adds document type and payload for Eval Memo to `generateDocumentSchema` and `generateDocxDocument` other places
- Adds `evalMemo` to models in `document-generation.ts`
- Adds jest mock response for `generateEvalMemoDocument`
- Sets jest timeout to 15000ms for DoW because timeouts were encountered for that document; used same amount elsewhere for consistency
- Renamed some recently created exports in `sampleTestData.ts` for consistency; we'd ignored an established convention for that last couple documents
Ticket: AT-9121

Add support for Evaluation Memo to HOTH API

---

document-generation/utils/sampleTestData.ts
hoth_api.yaml
models/document-generation/evaluation-memo.ts

This PR partially corrects a gap in expectations for property `exceptionToFairOpportunity` across the following PRs between @jeffsegal-ccpo and myself:
- https://github.com/dod-ccpo/atat-snow/pull/410
- https://github.com/dod-ccpo/atat-web-api/pull/1702 
- https://github.com/dod-ccpo/atat-web-api/pull/1710
The the remainder of the gap will be corrected in the Eval Plan script include in https://github.com/dod-ccpo/atat-snow/pull/413
Changes type of `exceptionToFairOpportunity` to boolean - _true_ for YES values (in column Fair Opportunity.exception_to_fair_opportunity), _false_ for NO_NONE and property is always included in JSON payload
Eval Memo document template requires no changes as written. Tested docgen locally with true and false values with positive results.  Use in document is …

Change Eval Memo JSON payload property 'exceptionToFairOpportunity' to boolean

---

.secrets.baseline
cfn-templates/sso-permission-sets.cf.yaml

this is to allow QA team ability to verify ec2 and s3 configs

updated the QA permissions for s3 and ec2 read and list permissions

---

models/document-generation.ts

The Eval Plan model is extended by that for Eval Memo.  This may resolve validation errors during docgen when there is no `sourceSelection` value.  Property `method` already contains this null option and it doesn't seem to cause the same validation error.
Ticket: AT-9120

Change Eval Plan validation model to allow 'null' for property 'sourceSelection'

---

document-generation/igce-document.ts

With recent change, DITCO user will have empty object for row 25 (External agency ordering fee)
Thus, formula `=(K24 + K25) * ${contractingShopFeePct}` will retrun underifned since K25 is null. 
Use the If statement to properly display the contracting office fee

AT-9007 - Fixed ditco fee returning undefined

---

document-generation/eval-memo-document.test.ts
document-generation/generate-document.test.ts
document-generation/utils/sampleTestData.ts
models/document-generation.ts

- adds additional sample payloads and unit tests for Eval Memo (EM) using the two most common variations - with and without exception to fair opportunity.
- The replaced singular sample payload had a (what I now understand to be) nonsensical combination with `exceptionToFairOpportunity`=_YES_ and values for both `sourceSelection` and `method` which come from Eval Plan (EP)
- adds unit tests for generate-document lambda for EM using the two new sample payloads
- corrects schema models for EP and EM that we pass to [middy](https://middy.js.org/) for validation during docgen
- this change allowed both of the new unit tests for the generate-document lambda to pass
- I believe this effectively isolated the validation errors we've seen in DSP Dev environment
- I witnessed similar oneOf …

Eval Memo improvements

---

models/cost-jobs.ts
models/document-generation.ts
models/provisioning-schemas.ts

Setting `additionalProperties` to `true` for the wrapper event schemas

AT-8454: Loosened event schema

---

.secrets.baseline
api/client/client.test.ts
api/client/client.ts
api/client/fixtures.ts
api/client/types.ts
api/cost/cost-request-fn.test.ts
api/provision/csp-update-taskorder.test.ts
api/provision/csp-update-taskorder.ts
api/util/common-test-fixtures.ts
api/util/csp-request.ts
document-generation/utils/dow.test.ts
jest.config.js
lib/atat-web-api-stack.ts
lib/constructs/provisioning-sfn-workflow.ts

Added all code necessary to implement `updateTaskOrder` functionality. All tests pass. Cleaned up some linter problems also.

AT-9692: Implement PUT /portfolios/{portfolioId}/task-orders/{taskOrderId}
